---
id: test_rnd_gen
kind: settings
seed: 42 # 0xF0CACC1E
greedy: true
obstacles: 30
time_max: 100
aux_path: ./test_rnd_gen.aux
size:
  width: 10
  height: 10
agents:
  number: 0
  stop_probability: 0.01
noise:
  octaves: 2
  persistence: 0.85
  cell_size: 10
  offset: 0.0
---
id: very_big
kind: settings
seed: 4039822366 # 0xF0CACC1E
greedy: true
obstacles: 10000
time_max: 100000
size:
  width: 10000
  height: 10000
agents:
  number: 1000
  stop_probability: 0.01
noise:
  octaves: 6
  persistence: 0.85
  cell_size: 12
---