---
id: test_rnd_gen
kind: settings
seed: 42 # 0xF0CACC1E
greedy: true
obstacles: 300
time_max: 100
aux_path: ./test_rnd_gen.aux
size:
  width: 100
  height: 100
agents:
  number: 80
  stop_probability: 0.001
noise:
  octaves: 3
  persistence: 0.85
  cell_size: 10
  offset: 0.0
---
id: very_big
kind: settings
seed: 4039822366 # 0xF0CACC1E
greedy: true
obstacles: 10000
time_max: 100000
size:
  width: 10000
  height: 10000
agents:
  number: 10000
  stop_probability: 0.01
noise:
  octaves: 6
  persistence: 0.85
  cell_size: 12
---