---
id: test_settings_1
kind: settings
seed: 45116156156
greedy: true
obstacles: 70
time_max: 100
aux_path: ./test_settings_1.aux
size:
  width: 30
  height: 30
agents:
  number: 15
  stop_probability: 0.01
noise:
  octaves: 4
  cell_size: 12
