---
id: test_rnd_gen
kind: settings
seed: 4039822366 # 0xF0CACC1E
greedy: true
obstacles: 150
time_max: 100
aux_path: ./test_rnd_gen.aux
size:
  width: 30
  height: 30
agents:
  number: 15
  stop_probability: 0.01
noise:
  octaves: 15
  persistence: 0.9
  cell_size: 12
---